---
# The settings below are relevant for all jammer types
# Choose the frequency range to operate in (1=2.4GHz, 2=5GHz) | default is 1
band: 1
# Set the jammer mode (1=constant, 2=sweeping, 3=random channel hopping) | default is 1
jammer: 1
# Define the jamming type (1=proactive, 2=reactive) | default is 1
jamming: 1
# Specify the jamming waveform (1=single tone, 2=swept sine, 3=gaussian noise) | default is 3
waveform: 2
# Input the jammer transmission power in dBm (Range: -40dBm to 13dBm) | default is 6dBm
power: 10
# Set the jamming duration per channel in seconds | default is 10 seconds
t_jamming: 5

# The options below may vary depending on the jammer selection
# Set the total operation time in seconds | default is 200 seconds
duration: 100 # Not applicable to constant jammer
# Define the spacing between channels in MHz (Range: 1MHz to 20MHz) | default is 20MHz
ch_dist: 1 # Not relevant for constant jammer or 5GHz band
# Set the frequency to target in MHz | default is 2462MHz
freq: 3440.5 # Only relevant for constant jammer
# Choose the channel allocation scheme (1=UNII-1, 2=UNII-2a, 3=UNII-2c, 4=UNII-3)
allocation: 1 # Only relevant for 5GHz band

