gnb:
  config: "../../configs/zmq/multi/gnb_zmq.yaml"

namespaces:
  - name: "ue1"
  - name: "ue2"
  - name: "ue3"

processes:
  - type: "clean"
    config_file: "../../../configs/zmq/multi/ue1_zmq.conf"
  - type: "clean"
    config_file: "../../../configs/zmq/multi/ue2_zmq.conf"
  - type: "clean"
    config_file: "../../../configs/zmq/multi/ue3_zmq.conf"
