services:
  srsue:
    container_name: srsran_ue
    image: srsran/ue
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    privileged: true
    env_file:
      - .env
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Access UHD images
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Store logs in /tmp
      - ue-storage:/tmp

    environment:
      - CONFIG=${UE_CONFIG_PATH:-configs/zmq/ue_zmq_docker.conf}
      - ARGS=${UE_ARGS}

    # Allow network connection for ZMQ
    ports:
       -  2000:2000/tcp
       -  2001:2001/tcp
    networks:
      -  srsue_network

  controller:
    container_name: controller
    image: controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONFIG=${UE_CONTROLLER_CONFIG}
    privileged: true
    build:
      context: controller
    env_file:
      - .env
    network_mode: "host"

  webui:
    container_name: webui
    image: webui
    build:
      context: webui
    env_file:
      - .env
    environment:
      - PORT=${WEBUI_PORT}
    network_mode: "host"
    depends_on:
      - controller

volumes:
  ue-storage:

networks:
  srsue_network:
    driver: bridge
  controller:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
